export interface OrderBandaLargaPJResponse {
  success: boolean;
  orders: OrderBandaLargaPJ[];
  total: number;
  page: number;
  perPage: number;
  totalPages: number;
  pedidos?: OrderBandaLargaPJ[];
  status_pos_venda_enum?: string[];
}

export interface OrderBandaLargaPJ {
  id: number;
  company?: string;
  order_number?: number | null;
  status: string;
  after_sales_status?: string | null;
  full_name: string;
  cpf: string;
  email: string;
  phone: string;
  additional_phone?: string | null;
  birth_date: string;
  mother_full_name: string;
  client_type: "PF" | "PJ";
  zip_code: string;
  address: string;
  address_number: string;
  address_complement?: string | null;
  address_block?: string | null;
  address_lot?: string | null;
  address_floor?: string | null;
  district: string;
  city: string;
  state: string;
  building_or_house?: string;
  cnpj?: string | null;
  company_legal_name?: string | null;
  plan: {
    name: string;
    value?: number;
    price?: number;
    id?: string;
    speed?: string;
  };
  due_day: string | number;
  terms_accepted: boolean;
  accept_offers: boolean;
  installation_preferred_date_one: string;
  installation_preferred_period_one: string;
  installation_preferred_date_two: string;
  installation_preferred_period_two: string;
  installation_preferred_date_three?: string | null;
  installation_preferred_period_three?: string | null;
  payment_method?: string;
  bank_name?: string;
  bank_branch?: string;
  bank_account_number?: string;
  has_fixed_line_portability?: boolean | null;
  fixed_line_number_to_port?: string | null;
  wants_fixed_ip?: boolean | null;
  phone_valid: boolean;
  operator: string;
  portability: string;
  portability_date: string;
  additional_phone_valid?: boolean | null;
  additional_operator?: string | null;
  additional_portability?: string | null;
  additional_portability_date?: string | null;
  is_email_valid?: boolean;
  found_via_range?: boolean | null;
  range_min?: string | null;
  range_max?: string | null;
  zip_code_type?: string | null;
  single_zip_code?: boolean | null;
  availability?: boolean | null | number;
  availability_pap?: boolean | null | number;
  ip_isp?: string | null;
  ip_org?: string | null;
  ip_as?: string | null;
  ip_access_type?: string | null;
  is_socio?: boolean | null;
  is_mei?: boolean | null;
  company_partners?: string | null;
  rfb_name?: string | null;
  rfb_birth_date?: string | null;
  rfb_mother_name?: string | null;
  rfb_gender?: string | null;
  client_ip: string;
  fingerprint_id?: string | null;
  whatsapp?: WhatsAppInfo | null;
  geolocation?: {
    success: boolean;
    latitude: string;
    longitude: string;
    maps_link: string;
    precision: string;
    queried_at: string;
    street_view_link: string;
    formatted_address: string;
  } | null;
  operators_availability?: object | null;
  pf_temperature?: number | null;
  credit?: number | string | null;
  cpf_second_call?: string | null;
  birth_date_second_call?: string | null;
  full_name_second_call?: string | null;
  mother_full_name_second_call?: string | null;
  number_attempts_second_call?: number | null;
  corporate_id?: string | null;
  responsible_consultant?: string | null;
  team?: string | null;
  crm_id?: number | null;
  consultant_notes?: string | null;
  consultant_observation?: string | null;
  manager_name?: string | null;
  manager?: string | null;
  is_consultation?: boolean | null;
  is_order?: boolean | null;
  consultation_id?: string | null;
  order_id?: string | null;
  highlight_top?: string | null;
  highlight_bottom?: string | null;
  url?: string | null;
  message?: string | null;
  installation?: string | null;
  service?: string | null;
  created_at: string;
  updated_at: string;
  // Campos legados (compatibilidade)
  credito?: number | string;
  cep_unico?: number;
  encontrado_via_range?: number;
  addressblock?: string;
  addresscomplement?: string;
  addressFloor?: string;
  addresslot?: string;
  addressnumber?: string;
  addressreferencepoint?: string;
  birthdate?: string;
  buildingorhouse?: number | string;
  cep?: string;
  consultor_responsavel?: string;
  consulta?: boolean;
  dueday?: number;
  equipe?: string;
  fingerprint?: {
    os: { name: string; version: string };
    browser: { name: string; version: string };
    device: string;
    timezone: string;
    timezone_name: string;
    timezone_offset: number;
    resolution?: { dpr: number; height: number; width: number };
  };
  fullname?: string;
  nome_receita?: string;
  data_de_nascimento_receita?: string;
  nome_da_mae_receita?: string;
  id_consult?: string;
  id_crm?: number;
  id_order?: string;
  id_vivo_corp?: string;
  motherfullname?: string;
  numero_valido?: boolean | number;
  ordernumber?: number;
  obs_consultor?: string;
  observacao_consultor?: string;
  operadora?: string;
  pedido?: boolean;
  phoneAdditional?: string;
  razaosocial?: string;
  status_pos_venda?: string;
  typeclient?: "PF" | "PJ";
  wantsFixedIp?: boolean;
  mei?: boolean;
  socio?: boolean;
  empresas?: string;
  device?: string;
  provider?: string;
  provedor?: string;
  so?: string;
  ip_tipo_acesso?: string;
  is_comercial?: boolean;
  nome_whatsapp?: string;
  recado?: string;
  avatar?: string;
  socios_empresas?: SociosEmpresas[];
  voz_fixa?: string;
  browser?: string;
  resolution?: string;
  numero_adicional_valido?: boolean | number;
  operadora_adicional?: string;
  temperatura_pf?: number;
  genero_receita?: string;
  portabilidade?: string;
  data_portabilidade?: string;
  portabilidade_adicional?: string;
  data_portabilidade_adicional?: string;
  second_call?: {
    attempts: {
      cpf: string;
      birthdate: string;
      fullname: string;
      motherfullname: string;
    }[];
    number_attempts: number;
  };
  geolocalizacao?: {
    sucesso: boolean;
    latitude: string;
    precisao: string;
    link_maps: string;
    longitude: string;
    consultado_em: string;
    cep_mais_proximo: string;
    link_street_view: string;
    endereco_formatado: string;
    tem_disponibilidade: boolean;
    distancia_km_ponto_mais_proximo: number;
  };
  debit: boolean;
}

export interface WhatsAppInfo {
  links: string[];
  avatar: string | null;
  numero: string | null;
  recado: string;
  sucesso: boolean;
  endereco: string | null;
  categoria: string;
  is_comercial: boolean;
  verificado_em: string;
  existe_no_whatsapp: boolean;
}

interface SociosEmpresas {
  cnpj: string;
  nome: string;
  porte: string;
}
export interface BandaLargaFilters {
  page?: string | number;
  per_page?: string | number;
  data_to?: string;
  data_from?: string;
  status?: string;
  availability?: string | number | boolean;
  cpf?: string;
  cnpj?: string;
  phone?: string;
  after_sales_status?: string | null;
  sort?: string;
  order?: "asc" | "desc";
  order_number?: string | number;
}
